number_2 = int(input("Сколько вы хотите увидеть пингвинов? "))
print("   _~_    " * number_2)
print("  (o o)   " * number_2)
print(" /  V  \  " * number_2)
print("/(  _  )\ " * number_2)
print("  ^^ ^^   " * number_2)

number_1 = int(input("Сколько зайчиков вы хотите увидеть? "))
print(" (\__/)" * number_1)
print("(='.'=)" * number_1)
print('(")_(")' * number_1)

number_3 = int(input("Сколько вы хотите увидеть рептилий? "))
print(" ~ ~ ~ ~ ~ ~ ~ ~ " * number_3)
print(" ~ ~ _,,,_ ~ ~ ~ " * number_3)
print(" ~ <°)3333><( ~ ~ " * number_3)
print(" ~ ~ \"?'''? ~ ~ ~  " * number_3)

number_4 = int(input("Сколько вы хотите увидеть рыбок? "))
print("~ ~ ~ ~ ~ ~ ~ ~ " * number_4)
print("~ ~ ~ ~ ~ ~ ~ ~ " * number_4)
print("~ ><((((o> ~ ~" * number_4)
print("~ ~ ~ ~ ~ ~ ~ ~ " * number_4)
print("~ ~ ~ ~ ~ ~ ~ ~ " * number_4)

number_5 = int(input("Сколько лягушек вы хотите увидеть? "))
print("``@..@   " * number_5)
print("`(_____) " * number_5)
print("(>____<) " * number_5)
print("^^~~~~^^ " * number_5)
